# name: Run demo-app tests

# on:
#   push:
#     branches:
#     - '**'
#     tags-ignore:
#     - '**'
#     paths:
#     - 'projects/demo-app/**'
#   pull_request:
#   workflow_call:
#   workflow_dispatch:

# concurrency:
#   group: run-demo-app-tests-group-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   ci_demo-app_tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v4

#       - name: Run tests
#         uses: ./.github/actions/run-tests
#         with:
#           working-directory: projects/demo-app
