name: Release
run-name: Release ${{ inputs.package }}${{ inputs.dry-run && ' (dry-run)' || '' }}

on:
    workflow_dispatch:
        inputs:
            package:
                description: Package
                required: true
                type: choice
                options:
                    - core
                    - layout
                    - list-loader
                    - message-box
                    - message-box-dialog
                    - numeric-stepper
                    - overlay
                    - search-container
                    - sidenav
                    - snackbar
                    - splitter
                    - status
                    - time-picker
                    - tooltip
                    - user-card
                    - user-tooltip
            dry-run:
                description: --dry-run
                type: boolean
                default: false

env:
    HUSKY: 0
    FORCE_COLOR: 3

jobs:
    ci_release:
        uses: dsi-hug/action/.github/workflows/action.yml@v1
        secrets:
            GH_USER_NAME: 'dsi-hug-bot'
            GH_USER_EMAIL: 'dsi-hug-bot@users.noreply.github.com'
            GH_TOKEN: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
        with:
            working-directory: 'projects/${{ inputs.package }}'
            dry-run: ${{ inputs.dry-run }}
            release: true
