name: Release
run-name: Release ${{ inputs.package }}${{ inputs.dry-run && ' (dry-run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        type: choice
        options:
          - core
          - list-loader
          - message-box
          - numeric-stepper
          - overlay
          - snackbar
          - splitter
          - status
          - time-picker
          - tooltip
      dry-run:
        description: --dry-run
        type: boolean
        default: false

env:
  HUSKY: 0
  FORCE_COLOR: 3

jobs:
  ci_release:
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    secrets:
      GH_USER_NAME: 'dsi-hug-bot'
      GH_USER_EMAIL: 'dsi-hug-bot@users.noreply.github.com'
      GH_TOKEN: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
    with:
      working-directory: 'projects/${{ inputs.package }}'
      dry-run: ${{ inputs.dry-run }}
      release: true

  ci_sync_peer_deps:
    needs: ci_release
    runs-on: 'ubuntu-latest'
    steps:
        - name: Checkout sources
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref_name }} # https://github.com/actions/checkout/issues/1327
            persist-credentials: false # https://github.com/semantic-release/semantic-release/issues/2636

        - name: Synchronize peer dependencies
          working-directory: 'scripts'
          env:
            GITHUB_TOKEN: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
          run: |
            git config user.name 'dsi-hug-bot'
            git config user.email 'dsi-hug-bot@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}@github.com/${{ github.repository }}
            npm --prefix . i chalk
            node ./sync-peer-deps.mjs
