name: Release
run-name: Release ${{ inputs.package }}${{ inputs.dry-run && ' (dry-run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        type: choice
        options:
          - core
          - list-loader
          - message-box
          - numeric-stepper
          - overlay
          - snackbar
          - splitter
          - status
          - time-picker
          - tooltip
      dry-run:
        description: --dry-run
        type: boolean
        default: false

env:
  HUSKY: 0

jobs:
  ci_release:
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    secrets:
      RELEASE_NPM_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
      RELEASE_GITHUB_TOKEN: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
    with:
      working-directory: 'projects/${{ inputs.package }}'
      dry-run: ${{ inputs.dry-run }}
      release: true
