name: Test message-box-dialog

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_message-box-dialog]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_message-box-dialog.yml'
            - 'projects/message-box-dialog/**'

concurrency:
    group: ci-test-message-box-dialog-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_message-box-dialog:
        uses: dsi-hug/actions/.github/workflows/action.yml@v3
        with:
            working-directory: projects/message-box-dialog
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            lint: true
            test: true
