name: Test snackbar

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_snackbar]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_snackbar.yml'
            - 'projects/snackbar/**'

concurrency:
    group: ci-test-snackbar-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_snackbar:
        uses: dsi-hug/actions/.github/workflows/action.yml@v3
        with:
            working-directory: projects/snackbar
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            lint: true
            test: true

    ci_test_deps:
        needs: ci_test_snackbar
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test status
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_status
