name: Test tooltip

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_test_tooltip.yml'
      - 'projects/tooltip/**'

concurrency:
  group: ci-test-tooltip-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_tooltip:
    if: "${{ !contains(github.event.head_commit.message, 'chore(release): publish') }}"
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    with:
      working-directory: projects/tooltip
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'
