name: Test date-picker

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_date-picker]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_date-picker.yml'
            - 'projects/date-picker/**'

concurrency:
    group: ci-test-date-picker-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_date-picker:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/date-picker
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[22]'
            lint: true
            test: true
