name: Test tooltip

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_tooltip]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_tooltip.yml'
            - 'projects/tooltip/**'

concurrency:
    group: ci-test-tooltip-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_tooltip:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/tooltip
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[20, 22]'
            lint: true
            test: true

    ci_test_deps:
        needs: ci_test_tooltip
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test user-tooltip
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_user-tooltip
