name: Test core

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_test_core.yml'
      - 'projects/core/**'

concurrency:
  group: ci-test-core-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_core:
    if: "${{ !contains(github.event.head_commit.message, 'chore(release): publish') }}"
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    with:
      working-directory: projects/core
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'

  ci_test_numeric_stepper:
    needs: ci_test_core
    uses: ./.github/workflows/ci_test_numeric-stepper.yml

  ci_test_overlay:
    needs: ci_test_core
    uses: ./.github/workflows/ci_test_overlay.yml

  ci_test_snackbar:
    needs: ci_test_core
    uses: ./.github/workflows/ci_test_snackbar.yml

  ci_test_splitter:
    needs: ci_test_core
    uses: ./.github/workflows/ci_test_splitter.yml
