name: Test search-container

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_test_search-container.yml'
      - 'projects/search-container/**'

concurrency:
  group: ci-test-search-container-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_search-container:
    uses: dsi-hug/actions/.github/workflows/action.yml@v2
    with:
      working-directory: projects/search-container
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'
      lint: true
      test: true
