name: Test sidenav

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_test_sidenav.yml'
      - 'projects/sidenav/**'

concurrency:
  group: ci-test-sidenav-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_sidenav:
    uses: dsi-hug/actions/.github/workflows/action.yml@v2
    with:
      working-directory: projects/sidenav
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'
      lint: true
      test: true

  ci_test_layout:
    needs: ci_test_sidenav
    uses: ./.github/workflows/ci_test_layout.yml
