name: Test core

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!release-please--branches--main'
    tags-ignore:
      - '**'
    paths:
      - 'projects/core/**'

concurrency:
  group: ci-test-core-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_core:
    uses: ./.github/workflows/ci_job.yml
    with:
      working-directory: projects/core
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'
