name: Test status

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_status]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_status.yml'
            - 'projects/status/**'

concurrency:
    group: ci-test-status-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_status:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/status
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[20, 22]'
            lint: true
            test: true
