name: Test numeric-stepper

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_numeric-stepper.yml'
            - 'projects/numeric-stepper/**'

concurrency:
    group: ci-test-numeric-stepper-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_numeric-stepper:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/numeric-stepper
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[18, 20]'
            lint: true
            test: true

    ci_test_time-picker:
        needs: ci_test_numeric-stepper
        uses: ./.github/workflows/ci_test_time-picker.yml
