name: Test tooltip

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_tooltip.yml'
            - 'projects/tooltip/**'

concurrency:
    group: ci-test-tooltip-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_tooltip:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/tooltip
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[20, 22]'
            lint: true
            test: true

    ci_test_user-tooltip:
        needs: ci_test_tooltip
        uses: ./.github/workflows/ci_test_user-tooltip.yml
