name: Test sidenav

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_sidenav]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_sidenav.yml'
            - 'projects/sidenav/**'

concurrency:
    group: ci-test-sidenav-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_sidenav:
        uses: dsi-hug/actions/.github/workflows/action.yml@v3
        with:
            working-directory: projects/sidenav
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            lint: true
            test: true

    ci_test_deps:
        needs: ci_test_sidenav
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test layout
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_layout
