name: Test core

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_core]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_core.yml'
            - 'projects/core/**'

concurrency:
    group: ci-test-core-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test-core:
        uses: dsi-hug/actions/.github/workflows/action.yml@v2
        with:
            working-directory: projects/core
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[18, 20]'
            lint: true
            test: true

    ci_test_deps:
        needs: ci_test-core
        runs-on: 'ubuntu-latest'
        steps:
            #
            # Not needed here because it will be triggered by `ci_test_sidenav`
            #
            # - name: Test test_layout
            #   uses: peter-evans/repository-dispatch@v3
            #   with:
            #       event-type: test_test_layout

            - name: Test message-box-dialog
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_message-box-dialog

            - name: Test numeric-stepper
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_numeric-stepper

            - name: Test overlay
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_overlay

            - name: Test search-container
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_search-container

            - name: Test sidenav
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_sidenav

            - name: Test snackbar
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_snackbar

            - name: Test splitter
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_splitter

            #
            # Not needed here because it will be triggered by `ci_test_snackbar`
            #
            # - name: Test t_status
            #   uses: peter-evans/repository-dispatch@v3
            #   with:
            #     event-type: test_status

            #
            # Not needed here because it will be triggered by `ci_test_numeric-stepper`
            #
            # - name: Test t_time-picker
            #   uses: peter-evans/repository-dispatch@v3
            #   with:
            #     event-type: test_time-picker

            - name: Test tooltip
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_tooltip

            #
            # Not needed here because it will be triggered by `ci_test_tooltip`
            #
            # - name: Test t_user-tooltip
            #   uses: peter-evans/repository-dispatch@v3
            #   with:
            #     event-type: test_user-tooltip
