name: Test snackbar

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_test_snackbar.yml'
      - 'projects/snackbar/**'

concurrency:
  group: ci-test-snackbar-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test_snackbar:
    if: "${{ !contains(github.event.head_commit.message, 'chore(release): publish') }}"
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    with:
      working-directory: projects/snackbar
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[18, 20]'
